# Generated by Django 5.2.6 on 2025-09-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_notes_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='username',
            new_name='name',
        ),
    ]
